
// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import tpo.labs.Utils;

public class ChangelangTest {
  private static WebDriver driver;
  private static Utils utils;

  @BeforeAll
  public static void setUp() {
    utils = new Utils();
    utils.setupDriver();
    driver = utils.getDriver();
  }

  @AfterAll
  public static void tearDown() {
    driver.quit();
  }

  @Test
  public void language() {
    driver.get("https://www.meetup.com/ru-RU/");
    driver.manage().window().setSize(new Dimension(853, 1064));
    {
      WebElement element = driver.findElement(By.xpath("//a[@id=\'register-link\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'page\']/header/div/div/div/div[3]/div/div/button/span")).click();
    {
      WebElement element = driver
          .findElement(By.xpath("//div[@id=\'page\']/header/div/div/div/div[3]/div/div/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".flex:nth-child(11) .block > circle")).click();
    driver.findElement(By.xpath("//div[3]/div/div/div/div/button")).click();

  }
}
