// Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import tpo.labs.Utils;

import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PickeEventTestSuiteTest {

  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static Utils utils;
    private static WebDriver driver;
  @BeforeAll
  public static void setUp(){
      utils = new Utils();
      utils.setupDriver();
      driver = utils.getDriver();
    //   wait = utils.getWaitTime();
    //  js = utils.getJsExecutor();

    //  homePage = new HomePage(driver);
  }
  
  @AfterAll
  public static void tearDown() {
    driver.quit();
  }
  @Test
  public void pickevent() {
    driver.get("https://www.meetup.com/ru-RU/");
    driver.manage().window().setSize(new Dimension(1728, 1079));
    {
      WebElement element = driver.findElement(By.xpath("//main[@id=\'main\']/div[2]/div/div/div[3]/div/a/div/img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//main[@id=\'main\']/div[2]/div/div/div[3]/div/a/div/img")).click();
    driver.findElement(By.cssSelector("#homepage-link path")).click();
    driver.findElement(By.xpath("//div[2]/a/div/img")).click();


  }
}
