// Generated by Selenium IDE

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import tpo.labs.Utils;

public class SearchTest {

  private static JavascriptExecutor js;
  private static Utils utils;
  private static WebDriver driver;

  @BeforeAll
  public static void setUp() {
    utils = new Utils();
    utils.setupDriver();
    driver = utils.getDriver();
    js = utils.getJsExecutor();
  }

  @Test
  public void search() {
    driver.get("https://www.meetup.com/ru-RU/");
    driver.manage().window().setSize(new Dimension(853, 1064));
    {
      WebElement element = driver
          .findElement(By.xpath("//div[@id=\'page\']/header/div/div/div/div[3]/div/div/button/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//main[@id=\'main\']/div[2]/div/div/div/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//main[@id=\'main\']/div[2]/div/div/div/a")).click();
    driver.findElement(By.xpath("//form[@id=\'search-form\']/div/div/div/input")).click();
    driver.findElement(By.xpath("//form[@id=\'search-form\']/div/div/div/input")).sendKeys("Go");
    {
      WebElement element = driver.findElement(By.cssSelector("#search-button .injected-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#search-button .injected-svg")).click();
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'location-search-submit\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,241)");

  }
}
