// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import tpo.labs.Utils;

public class UkTest {

  private static Utils utils;
  private static WebDriver driver;

  @BeforeAll
  public static void setUp() {
    utils = new Utils();
    utils.setupDriver();
    driver = utils.getDriver();
  }

  @AfterAll
  public static void tearDown() {
    driver.quit();
  }

  @Test
  public void searchUK() {
    driver.get("https://www.meetup.com/ru-RU/");
    driver.manage().window().setSize(new Dimension(1728, 1079));
    driver.findElement(By.xpath("//form[@id=\'search-form\']/div/div[2]/div/div/div/div/input")).click();
    driver.findElement(By.xpath("//form[@id=\'search-form\']/div/div[2]/div/div/div/div/input")).sendKeys("Nigg");
    {
      WebElement element = driver.findElement(By.xpath("//main[@id=\'main\']/div[2]/div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
  }
}
